export const SIGN_IN_ADMIN_REQUEST = "SIGN_IN_ADMIN_REQUEST";
export const SIGN_IN_ADMIN_SUCCESS = "SIGN_IN_ADMIN_SUCCESS";
export const SIGN_IN_ADMIN_FAILURE = "SIGN_IN_ADMIN_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_ALL_USERS_COUNT_REQUEST = "GET_ALL_USERS_COUNT_REQUEST";
export const GET_ALL_USERS_COUNT_SUCCESS = "GET_ALL_USERS_COUNT_SUCCESS";
export const GET_ALL_USERS_COUNT_FAILURE = "GET_ALL_USERS_COUNT_FAILURE";